import type { ModuleConfig } from "@/components/demo/module-view";
import type { View } from "@/components/demo/sidebar";

export const moduleConfigs: Partial<Record<View, ModuleConfig>> = {
  "work-requests": {
    title: "Work Requests",
    description: "Tiếp nhận yêu cầu sửa chữa từ người dùng, QR code và hotline nội bộ.",
    primaryAction: "Tạo yêu cầu",
    columns: ["Mã", "Nội dung", "Người gửi", "Khu vực", "Trạng thái", "Ngày"],
    stats: [
      { label: "Yêu cầu mới", value: "18", tone: "blue" },
      { label: "Đã chuyển WO", value: "11", tone: "green" },
      { label: "Chờ duyệt", value: "5", tone: "amber" },
      { label: "Quá hạn", value: "2", tone: "red" },
    ],
    rows: [
      row("REQ-001", "Rò nước tại khu vệ sinh tầng 2", "Lễ tân", "Tòa A", "Pending", "05/06/2026", "SLA 4h"),
      row("REQ-002", "Đèn hành lang chập chờn", "Bảo vệ ca đêm", "Tòa B", "Approved", "05/06/2026", "SLA 8h"),
      row("REQ-003", "Máy lạnh phòng họp không lạnh", "Phòng kinh doanh", "Tầng 5", "In Progress", "04/06/2026", "SLA 6h"),
    ],
    features: ["Tạo WO từ request", "Gắn ảnh hiện trường", "Phân loại ưu tiên và SLA"],
  },
  issues: {
    title: "Issues",
    description: "Theo dõi sự cố vận hành, mức độ ảnh hưởng và phương án xử lý.",
    primaryAction: "Tạo sự cố",
    columns: ["Mã", "Sự cố", "Người phụ trách", "Khu vực", "Trạng thái", "Ngày"],
    stats: [
      { label: "Đang mở", value: "9", tone: "red" },
      { label: "Đang xử lý", value: "14", tone: "amber" },
      { label: "Đã đóng", value: "63", tone: "green" },
      { label: "MTTR", value: "3.2h", tone: "blue" },
    ],
    rows: [
      row("ISS-001", "Áp suất bơm thấp bất thường", "Nguyễn Văn A", "Phòng bơm", "In Progress", "05/06/2026", "P1"),
      row("ISS-002", "Cửa cuốn khu nhập hàng kẹt ray", "Trần Văn B", "Kho C", "Pending", "05/06/2026", "P2"),
      row("ISS-003", "UPS cảnh báo battery fault", "Lê Văn C", "Data room", "Blocked", "04/06/2026", "P1"),
    ],
    features: ["Phân tích nguyên nhân", "Liên kết task/WO", "Biên bản xử lý sự cố"],
  },
  "response-issues": {
    title: "Response Issues",
    description: "Màn hình tiếp nhận phản hồi và điều phối đội xử lý sự cố.",
    primaryAction: "Ghi nhận phản hồi",
    columns: ["Mã", "Phản hồi", "Người xử lý", "Nguồn", "Trạng thái", "Ngày"],
    stats: [
      { label: "Phản hồi hôm nay", value: "21", tone: "blue" },
      { label: "Đã phản hồi", value: "17", tone: "green" },
      { label: "Chờ xác minh", value: "4", tone: "amber" },
      { label: "Ưu tiên cao", value: "3", tone: "red" },
    ],
    rows: [
      row("RSP-001", "Khách báo mùi khét tại tầng hầm", "Đội MEP", "Mobile", "In Progress", "05/06/2026", "15 phút"),
      row("RSP-002", "Nhà thầu cần xác nhận vật tư", "Quản lý kho", "Web", "Pending", "05/06/2026", "30 phút"),
      row("RSP-003", "Người dùng xác nhận đã sửa xong", "CSKH", "Email", "Completed", "04/06/2026", "Hoàn tất"),
    ],
    features: ["Danh sách báo cáo", "Panel chi tiết", "Theo dõi phản hồi khách hàng"],
  },
  planner: {
    title: "Planner",
    description: "Lập lịch bảo trì theo nguồn lực, ca làm việc và mức độ xung đột.",
    primaryAction: "Lên lịch",
    columns: ["Mã", "Kế hoạch", "Tổ đội", "Khu vực", "Trạng thái", "Ngày"],
    stats: [
      { label: "Lịch tuần này", value: "32", tone: "blue" },
      { label: "Không xung đột", value: "27", tone: "green" },
      { label: "Cần điều phối", value: "5", tone: "amber" },
      { label: "Thiếu nhân sự", value: "2", tone: "red" },
    ],
    rows: [
      row("PLN-001", "PM máy bơm cụm A", "Team MEP 1", "Tòa A", "Scheduled", "06/06/2026", "2 kỹ thuật"),
      row("PLN-002", "Kiểm tra PCCC tháng 6", "Team Safety", "Toàn khu", "Approved", "07/06/2026", "4 kỹ thuật"),
      row("PLN-003", "Bảo dưỡng HVAC", "Team HVAC", "Tầng 3-5", "Warning", "08/06/2026", "Trùng ca"),
    ],
    features: ["Timeline nguồn lực", "Cảnh báo xung đột", "Kéo thả lịch bảo trì"],
  },
  tasks: {
    title: "Tasks",
    description: "Quản lý công việc bảo trì theo bảng, kanban và timeline.",
    primaryAction: "Tạo task",
    columns: ["Mã", "Task", "Kỹ thuật viên", "Tài sản", "Trạng thái", "Hạn"],
    stats: [
      { label: "Tổng task", value: "86", tone: "blue" },
      { label: "Hoàn tất", value: "51", tone: "green" },
      { label: "Đang làm", value: "28", tone: "amber" },
      { label: "Trễ hạn", value: "7", tone: "red" },
    ],
    rows: [
      row("TSK-001", "Thay bạc đạn bơm A01", "Nguyễn Văn A", "Máy bơm A01", "In Progress", "05/06/2026", "70%"),
      row("TSK-002", "Vệ sinh lưới lọc AHU", "Trần Văn B", "AHU-03", "Pending", "06/06/2026", "0%"),
      row("TSK-003", "Nghiệm thu thang máy", "Lê Văn C", "Lift B02", "Completed", "04/06/2026", "100%"),
    ],
    features: ["Kanban task", "Checklist nghiệm thu", "Ghi nhận chi phí phát sinh"],
    detailTitle: "Task Detail",
  },
  "your-tasks": {
    title: "Your Tasks",
    description: "Danh sách công việc cá nhân của kỹ thuật viên đang đăng nhập.",
    primaryAction: "Nhận task",
    columns: ["Mã", "Task", "Người giao", "Tài sản", "Trạng thái", "Hạn"],
    stats: [
      { label: "Của tôi", value: "12", tone: "blue" },
      { label: "Xong hôm nay", value: "4", tone: "green" },
      { label: "Đang làm", value: "6", tone: "amber" },
      { label: "Quá hạn", value: "2", tone: "red" },
    ],
    rows: [
      row("MY-001", "Kiểm tra rung động motor", "Quản lý MEP", "Motor M-12", "In Progress", "05/06/2026", "Ca sáng"),
      row("MY-002", "Chụp ảnh sau sửa chữa", "Supervisor", "AHU-03", "Pending", "05/06/2026", "Mobile"),
      row("MY-003", "Ký xác nhận nghiệm thu", "QA", "Lift B02", "Scheduled", "06/06/2026", "E-sign"),
    ],
    features: ["Checklist cá nhân", "Cập nhật trạng thái nhanh", "Upload ảnh từ hiện trường"],
  },
  facilities: {
    title: "Facilities",
    description: "Cấu trúc địa điểm, tòa nhà, tầng, phòng và khu vực vận hành.",
    primaryAction: "Thêm facility",
    columns: ["Mã", "Facility", "Quản lý", "Vị trí", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Tòa nhà", value: "8", tone: "blue" },
      { label: "Đang hoạt động", value: "7", tone: "green" },
      { label: "Bảo trì", value: "1", tone: "amber" },
      { label: "Tài sản gắn kèm", value: "342", tone: "blue" },
    ],
    rows: [
      row("FAC-001", "Tòa nhà A", "Nguyễn Văn A", "Quận 1", "Active", "05/06/2026", "128 assets"),
      row("FAC-002", "Kho trung tâm", "Trần Văn B", "Bình Dương", "Active", "04/06/2026", "92 assets"),
      row("FAC-003", "Khu kỹ thuật hầm B2", "Lê Văn C", "Tòa B", "Warning", "03/06/2026", "24 assets"),
    ],
    features: ["Cây facility", "QR code khu vực", "Liên kết asset con"],
  },
  enterprises: {
    title: "Enterprises",
    description: "Quản lý khách hàng, đơn vị thuê, nhà vận hành và phân loại kinh doanh.",
    primaryAction: "Thêm enterprise",
    columns: ["Mã", "Đơn vị", "Người liên hệ", "Khu vực", "Trạng thái", "Ngày"],
    stats: [
      { label: "Doanh nghiệp", value: "36", tone: "blue" },
      { label: "Đang hoạt động", value: "34", tone: "green" },
      { label: "Chờ duyệt", value: "2", tone: "amber" },
      { label: "Hợp đồng sắp hết", value: "4", tone: "red" },
    ],
    rows: [
      row("ENT-001", "Công ty ABC Retail", "Ms. Hạnh", "Tòa A", "Active", "05/06/2026", "Retail"),
      row("ENT-002", "Văn phòng DEF", "Mr. Minh", "Tầng 8", "Active", "04/06/2026", "Office"),
      row("ENT-003", "Nhà thầu GHI", "Mr. Long", "Khu kỹ thuật", "Pending", "03/06/2026", "Vendor"),
    ],
    features: ["Phân loại khách hàng", "Xuất Excel", "Gắn facility thuê"],
  },
  "inventory-categories": {
    title: "Inventory Categories",
    description: "Cây danh mục vật tư, phụ tùng, nhóm tồn kho và định mức.",
    primaryAction: "Thêm danh mục",
    columns: ["Mã", "Danh mục", "Quản lý", "Nhóm", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Danh mục", value: "42", tone: "blue" },
      { label: "Có định mức", value: "31", tone: "green" },
      { label: "Cần rà soát", value: "6", tone: "amber" },
      { label: "Ẩn", value: "5", tone: "red" },
    ],
    rows: [
      row("CAT-001", "Spare Parts", "Kho vận", "Maintenance", "Active", "05/06/2026", "96 items"),
      row("CAT-002", "Electrical", "MEP", "Technical", "Active", "04/06/2026", "44 items"),
      row("CAT-003", "Consumables", "Procurement", "Operation", "Warning", "03/06/2026", "18 items"),
    ],
    features: ["Cây danh mục cha-con", "Quick create", "Áp định mức tồn kho"],
  },
  vendors: {
    title: "Vendors",
    description: "Quản lý nhà cung cấp, SLA, đầu mối liên hệ và lịch sử mua hàng.",
    primaryAction: "Thêm vendor",
    columns: ["Mã", "Nhà cung cấp", "Liên hệ", "Khu vực", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Vendor", value: "28", tone: "blue" },
      { label: "Đạt SLA", value: "24", tone: "green" },
      { label: "Cần đánh giá", value: "3", tone: "amber" },
      { label: "Tạm khóa", value: "1", tone: "red" },
    ],
    rows: [
      row("VEN-001", "Cơ điện Minh Long", "Mr. Long", "TP.HCM", "Active", "05/06/2026", "SLA 98%"),
      row("VEN-002", "Daikin Service", "Ms. Linh", "Miền Nam", "Active", "04/06/2026", "SLA 95%"),
      row("VEN-003", "PCCC An Toàn", "Mr. Hải", "Toàn quốc", "Warning", "03/06/2026", "SLA 82%"),
    ],
    features: ["Đánh giá vendor", "Danh mục cung ứng", "Lịch sử PO"],
  },
  warehouses: {
    title: "Warehouse",
    description: "Quản lý kho, vị trí bin, tồn vật tư và cấp phát cho work order.",
    primaryAction: "Thêm kho",
    columns: ["Mã", "Kho", "Thủ kho", "Vị trí", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Kho", value: "6", tone: "blue" },
      { label: "Đang mở", value: "6", tone: "green" },
      { label: "Cảnh báo tồn", value: "9", tone: "amber" },
      { label: "Hết hàng", value: "2", tone: "red" },
    ],
    rows: [
      row("WH-001", "Kho kỹ thuật A", "Nguyễn Văn A", "Tầng B1", "Active", "05/06/2026", "1,245 SKU"),
      row("WH-002", "Kho vật tư PCCC", "Trần Văn B", "Tòa B", "Active", "04/06/2026", "312 SKU"),
      row("WH-003", "Kho dự phòng", "Lê Văn C", "Bình Dương", "Warning", "03/06/2026", "Low stock"),
    ],
    features: ["Tồn theo bin", "Cấp phát vật tư", "Điều chuyển kho"],
  },
  "stock-movement": {
    title: "Stock Movement",
    description: "Theo dõi nhập, xuất, điều chuyển và hoàn vật tư từ work order.",
    primaryAction: "Tạo phiếu",
    columns: ["Mã", "Phiếu kho", "Người tạo", "Kho", "Trạng thái", "Ngày"],
    stats: [
      { label: "Phiếu tháng này", value: "74", tone: "blue" },
      { label: "Đã duyệt", value: "61", tone: "green" },
      { label: "Chờ duyệt", value: "10", tone: "amber" },
      { label: "Lệch tồn", value: "3", tone: "red" },
    ],
    rows: [
      row("SM-001", "Xuất vật tư cho WO-001", "Kho vận", "Kho A", "Approved", "05/06/2026", "-12 items"),
      row("SM-002", "Nhập dầu nhớt 5W-30", "Procurement", "Kho A", "Completed", "04/06/2026", "+120 liters"),
      row("SM-003", "Điều chuyển contactor", "Supervisor", "Kho B", "Pending", "03/06/2026", "24 pcs"),
    ],
    features: ["Nhập/xuất/điều chuyển", "Liên kết Work Order", "Kiểm kê tồn"],
  },
  "stock-movement-stats": {
    title: "Stock Statistics",
    description: "Thống kê tồn kho, biến động vật tư và nhóm cảnh báo cần mua.",
    primaryAction: "Tạo báo cáo",
    columns: ["Mã", "Báo cáo", "Người tạo", "Phạm vi", "Trạng thái", "Ngày"],
    stats: [
      { label: "Giá trị tồn", value: "2.4B", tone: "blue" },
      { label: "SKU ổn định", value: "1,018", tone: "green" },
      { label: "Sắp hết", value: "37", tone: "amber" },
      { label: "Hết hàng", value: "8", tone: "red" },
    ],
    rows: [
      row("ST-001", "Tồn kho theo warehouse", "CFO", "Toàn hệ thống", "Completed", "05/06/2026", "6 kho"),
      row("ST-002", "Top vật tư tiêu hao", "Kho vận", "Tháng 6", "Completed", "04/06/2026", "Top 20"),
      row("ST-003", "Danh sách cần mua", "Procurement", "Tuần 23", "Warning", "03/06/2026", "37 SKU"),
    ],
    features: ["Biểu đồ biến động", "Cảnh báo reorder", "Báo cáo tồn theo kho"],
  },
  "purchase-requests": {
    title: "Purchase Requests",
    description: "Đề xuất mua hàng từ định mức tồn kho và nhu cầu work order.",
    primaryAction: "Tạo PR",
    columns: ["Mã", "Đề xuất", "Người yêu cầu", "Kho/WO", "Trạng thái", "Ngày"],
    stats: [
      { label: "PR mở", value: "19", tone: "blue" },
      { label: "Đã duyệt", value: "12", tone: "green" },
      { label: "Chờ duyệt", value: "5", tone: "amber" },
      { label: "Bị từ chối", value: "2", tone: "red" },
    ],
    rows: [
      row("PR-001", "Mua bộ lọc AHU", "Team HVAC", "Kho A", "Pending", "05/06/2026", "18,000,000"),
      row("PR-002", "Mua dầu thủy lực", "Team MEP", "WO-001", "Approved", "04/06/2026", "9,500,000"),
      row("PR-003", "Bổ sung contactor", "Kho vận", "Kho B", "Draft", "03/06/2026", "4,200,000"),
    ],
    features: ["Luồng duyệt PR", "Gợi ý từ low stock", "Theo dõi ngân sách"],
  },
  users: {
    title: "Users",
    description: "Quản lý người dùng, phòng ban, vai trò và trạng thái tài khoản.",
    primaryAction: "Thêm user",
    columns: ["Mã", "Người dùng", "Email/Quản lý", "Phòng ban", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "User", value: "128", tone: "blue" },
      { label: "Online", value: "42", tone: "green" },
      { label: "Chờ kích hoạt", value: "8", tone: "amber" },
      { label: "Khóa", value: "3", tone: "red" },
    ],
    rows: [
      row("USR-001", "Nguyễn Văn A", "a.nguyen@demo.vn", "MEP", "Online", "05/06/2026", "Technician"),
      row("USR-002", "Trần Thị B", "b.tran@demo.vn", "Warehouse", "Active", "04/06/2026", "Storekeeper"),
      row("USR-003", "Lê Văn C", "c.le@demo.vn", "Admin", "Pending", "03/06/2026", "Supervisor"),
    ],
    features: ["QR nhân sự", "Phân quyền vai trò", "Đổi mật khẩu"],
  },
  roles: {
    title: "Roles",
    description: "Thiết lập vai trò, quyền xem/sửa/xóa và phân quyền theo module.",
    primaryAction: "Thêm role",
    columns: ["Mã", "Vai trò", "Người quản lý", "Phạm vi", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Vai trò", value: "9", tone: "blue" },
      { label: "Đang dùng", value: "8", tone: "green" },
      { label: "Nháp", value: "1", tone: "amber" },
      { label: "Quyền đặc biệt", value: "2", tone: "red" },
    ],
    rows: [
      row("ROL-001", "Super Admin", "IT", "All modules", "Active", "05/06/2026", "Full access"),
      row("ROL-002", "Maintenance Manager", "Operation", "WO/Task/Asset", "Active", "04/06/2026", "Approve"),
      row("ROL-003", "Technician", "Operation", "Task/Mobile", "Active", "03/06/2026", "Update only"),
    ],
    features: ["Ma trận quyền", "Gán role theo user", "Ẩn module theo quyền"],
  },
  "video-call": {
    title: "Video Call",
    description: "Tạo phòng hỗ trợ từ xa giữa kỹ thuật viên hiện trường và chuyên gia.",
    primaryAction: "Tạo phòng",
    columns: ["Mã", "Phòng", "Người chủ trì", "Khu vực", "Trạng thái", "Thời gian"],
    stats: [
      { label: "Phòng hôm nay", value: "7", tone: "blue" },
      { label: "Đang online", value: "3", tone: "green" },
      { label: "Đã lên lịch", value: "4", tone: "amber" },
      { label: "Mất kết nối", value: "1", tone: "red" },
    ],
    rows: [
      row("VC-001", "Hỗ trợ sửa bơm A01", "Supervisor MEP", "Phòng bơm", "Online", "05/06/2026", "4 người"),
      row("VC-002", "Nghiệm thu HVAC", "QA", "Tầng 5", "Scheduled", "05/06/2026", "14:00"),
      row("VC-003", "Tư vấn vendor PCCC", "Safety", "Hầm B2", "Completed", "04/06/2026", "32 phút"),
    ],
    features: ["Tạo/join room", "Liên kết Work Order", "Chia sẻ hiện trường"],
  },
  settings: {
    title: "Settings",
    description: "Thiết lập danh mục asset, maintenance, department và business classification.",
    primaryAction: "Thêm cấu hình",
    columns: ["Mã", "Cấu hình", "Người quản lý", "Nhóm", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Danh mục", value: "24", tone: "blue" },
      { label: "Đang áp dụng", value: "22", tone: "green" },
      { label: "Cần rà soát", value: "2", tone: "amber" },
      { label: "Lỗi mapping", value: "0", tone: "red" },
    ],
    rows: [
      row("SET-001", "Asset Category", "Admin", "Asset", "Active", "05/06/2026", "12 loại"),
      row("SET-002", "Maintenance Type", "Admin", "WO", "Active", "04/06/2026", "8 loại"),
      row("SET-003", "Department", "HR", "User", "Active", "03/06/2026", "9 phòng ban"),
    ],
    features: ["Danh mục hệ thống", "Cấu hình nghiệp vụ", "Bật/tắt module demo"],
  },
  backups: {
    title: "Backup & Restore",
    description: "Theo dõi bản sao lưu, phục hồi dữ liệu và trạng thái job hệ thống.",
    primaryAction: "Tạo backup",
    columns: ["Mã", "Bản backup", "Người tạo", "Máy chủ", "Trạng thái", "Ngày"],
    stats: [
      { label: "Backup", value: "31", tone: "blue" },
      { label: "Thành công", value: "29", tone: "green" },
      { label: "Đang chạy", value: "1", tone: "amber" },
      { label: "Thất bại", value: "1", tone: "red" },
    ],
    rows: [
      row("BAK-001", "Daily backup 05/06", "System", "Primary DB", "Completed", "05/06/2026", "1.8 GB"),
      row("BAK-002", "Weekly backup W23", "System", "Backup node", "Completed", "02/06/2026", "9.4 GB"),
      row("BAK-003", "Manual restore test", "Admin", "Staging", "Failed", "01/06/2026", "Timeout"),
    ],
    features: ["Tạo backup thủ công", "Khôi phục bản lưu", "Theo dõi trạng thái job"],
  },
  profiles: {
    title: "Profiles",
    description: "Thông tin tài khoản demo, đổi mật khẩu và cấu hình hiển thị.",
    primaryAction: "Cập nhật profile",
    columns: ["Mã", "Thông tin", "Liên hệ", "Nhóm", "Trạng thái", "Cập nhật"],
    stats: [
      { label: "Phiên đăng nhập", value: "1", tone: "blue" },
      { label: "Thông tin đủ", value: "95%", tone: "green" },
      { label: "Thông báo", value: "12", tone: "amber" },
      { label: "Cảnh báo", value: "0", tone: "red" },
    ],
    rows: [
      row("PRO-001", "Admin Demo", "admin@demo.vn", "Enterprise A", "Active", "05/06/2026", "Super Admin"),
      row("PRO-002", "Ngôn ngữ", "Tiếng Việt", "Preference", "Active", "05/06/2026", "VI"),
      row("PRO-003", "Bảo mật", "Đổi mật khẩu", "Security", "Pending", "05/06/2026", "2FA off"),
    ],
    features: ["Sửa profile", "Đổi mật khẩu", "Tùy chọn ngôn ngữ"],
  },
};

function row(
  id: string,
  name: string,
  owner: string,
  location: string,
  status: string,
  date: string,
  metric: string,
) {
  return {
    id,
    name,
    owner,
    location,
    status,
    date,
    metric,
    note: `${name} được dựng bằng dữ liệu mẫu để trình diễn luồng nghiệp vụ không cần backend.`,
  };
}
